server:
  port: 8003
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
accessKeyId: "LTAI4Fk2YdPh2q6xfCZTfgjq"
accessKeySecret: "mrFycyHGAyw3d7kCBnoPW9ntyI6YVL"



